import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Check, CircleAlert, HandCoins, LogOut, Plus, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { toast } from "sonner";

const money = (cents: number) => `$${(cents / 100).toFixed(2)}`;

export default function MemberHub() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const dashboard = trpc.member.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const saveProfile = trpc.member.saveProfile.useMutation({ onSuccess: () => { toast.success("Profile saved"); dashboard.refetch(); } });
  const createRequest = trpc.member.createRequest.useMutation({ onSuccess: () => { toast.success("Loan request posted"); dashboard.refetch(); setForm({ ...form, amount: "", notes: "" }); } });
  const createOffer = trpc.member.createOffer.useMutation({ onSuccess: () => { toast.success("Lender availability posted"); dashboard.refetch(); setOffer({ ...offer, amount: "", notes: "" }); } });
  const confirmRepayment = trpc.member.confirmRepayment.useMutation({ onSuccess: () => { toast.success("Repayment confirmation recorded"); dashboard.refetch(); } });
  const [profileOpen, setProfileOpen] = useState(false);
  const [formOpen, setFormOpen] = useState<"request" | "offer" | null>(null);
  const [form, setForm] = useState({ amount: "", repaymentAt: "", payIdType: "phone" as "phone" | "email" | "abn", notes: "" });
  const [offer, setOffer] = useState({ amount: "", availableUntil: "", minimumTrustScore: "50", payIdType: "phone" as "phone" | "email" | "abn", notes: "" });
  const [profile, setProfile] = useState({ displayName: user?.name ?? "", state: "", paydayCycle: "fortnightly" as "weekly" | "fortnightly" | "monthly", intent: "both" as "borrow" | "lend" | "both", bio: "", payIdType: "phone" as "phone" | "email" | "abn" });
  const currentProfile = dashboard.data?.profile;
  const currentMembership = dashboard.data?.membership;
  const trust = currentProfile?.trustScore ?? 50;
  const openRequests = useMemo(() => dashboard.data?.requests.filter((item) => item.status === "open") ?? [], [dashboard.data]);
  const activeOffers = useMemo(() => dashboard.data?.offers.filter((item) => item.status === "active") ?? [], [dashboard.data]);

  if (loading) return <div className="hub-loading">Loading your member hub…</div>;
  if (!isAuthenticated) return <main className="auth-gate"><ShieldCheck size={36} /><h1>Sign in to join the network.</h1><p>Your member hub keeps profiles, requests, matches, and repayment confirmations in one private place.</p><button className="button button-primary" onClick={startLogin}>Sign in with Manus <ArrowRight size={16} /></button></main>;

  const submitProfile = () => saveProfile.mutate({ ...profile, state: profile.state || undefined, bio: profile.bio || undefined });
  const submitRequest = () => createRequest.mutate({ amountCents: Math.round(Number(form.amount) * 100), repaymentAt: new Date(form.repaymentAt), payIdType: form.payIdType, notes: form.notes || undefined });
  const submitOffer = () => createOffer.mutate({ amountCents: Math.round(Number(offer.amount) * 100), availableUntil: new Date(offer.availableUntil), minimumTrustScore: Number(offer.minimumTrustScore), payIdType: offer.payIdType, notes: offer.notes || undefined });

  return <div className="hub-shell">
    <header className="hub-header section-wrap"><a className="brand" href="/"><img src="/manus-storage/payday-mate-logo_de638b7a.png" alt="Payday Mate" /><span>Payday <strong>mate</strong></span></a><div className="hub-user"><span>{user?.name ?? "Member"}</span><button className="icon-button" aria-label="Sign out" onClick={() => logout()}><LogOut size={17} /></button></div></header>
    <main className="section-wrap hub-main">
      <div className="hub-intro"><div><p className="eyebrow"><span className="signal green" /> Member hub</p><h1>Make payday work<br /><em>both ways.</em></h1><p>Keep your profile clear, find a fit, and confirm every step. Payday Mate never holds or moves member funds.</p></div><div className="trust-card"><div className="trust-ring"><span>{trust}</span><small>/100</small></div><div><strong>Trust score</strong><p>Start small. Repay early. Communicate clearly.</p></div></div></div>
      <section className="hub-grid">
        <article className="panel profile-panel"><div className="panel-heading"><div><p className="eyebrow"><span className="signal blue" /> Your profile</p><h2>{currentProfile?.displayName ?? "Set up your profile"}</h2></div><UserRound size={21} /></div>{currentProfile ? <><p className="profile-copy">{currentProfile.bio || "Add a short introduction so the community knows your rhythm."}</p><div className="profile-meta"><span>{currentProfile.state || "Australia"}</span><span>{currentProfile.paydayCycle}</span><span>{currentProfile.intent}</span></div></> : <p className="profile-copy">Share your state, payday cycle, and whether you are here to borrow, lend, or both.</p>}<button className="button button-soft" onClick={() => { setProfile({ displayName: currentProfile?.displayName ?? user?.name ?? "", state: currentProfile?.state ?? "", paydayCycle: currentProfile?.paydayCycle ?? "fortnightly", intent: currentProfile?.intent ?? "both", bio: currentProfile?.bio ?? "", payIdType: currentProfile?.payIdType ?? "phone" }); setProfileOpen(true); }}>{currentProfile ? "Edit profile" : "Complete profile"} <ArrowRight size={15} /></button></article>
        <article className="panel membership-panel"><div className="panel-heading"><div><p className="eyebrow"><span className="signal yellow" /> Access</p><h2>{currentMembership?.tier ? `${currentMembership.tier} member` : "Free member"}</h2></div><Sparkles size={21} /></div><p className="profile-copy">Your current access controls which community spaces and lending limits are available.</p><div className="membership-pills"><span className="status-pill">{currentMembership?.status ?? "active"}</span><span>PayID stays private</span></div><a className="button button-primary" href="/#tiers">View membership tiers <ArrowRight size={15} /></a></article>
      </section>
      <section className="market-section"><div className="section-heading split-heading"><div><p className="eyebrow"><span className="signal red" /> The lending board</p><h2>Find a clear fit.</h2></div><p>Posts show the amount, timing, trust score, and PayID type only. Keep actual PayID details in private DMs after a confirmed match.</p></div><div className="board-actions"><button className="button button-primary" onClick={() => setFormOpen("request")}><Plus size={16} /> Post a loan request</button><button className="button button-soft" onClick={() => setFormOpen("offer")}><HandCoins size={16} /> Offer lender availability</button></div><div className="board-grid"><div><h3>Open requests <span>{openRequests.length}</span></h3>{openRequests.length ? openRequests.map((item) => <article className="board-card" key={`request-${item.id}`}><div><strong>{money(item.amountCents)}</strong><span>repay {new Date(item.repaymentAt).toLocaleDateString("en-AU")}</span></div><div className="board-card-meta"><span>Trust {item.trustScoreSnapshot}</span><span>{item.payIdType} PayID</span></div><p>{item.notes || "No additional notes."}</p></article>) : <div className="empty-board">No open requests yet. Your post can start the board.</div>}</div><div><h3>Lender availability <span>{activeOffers.length}</span></h3>{activeOffers.length ? activeOffers.map((item) => <article className="board-card" key={`offer-${item.id}`}><div><strong>{money(item.amountCents)}</strong><span>until {new Date(item.availableUntil).toLocaleDateString("en-AU")}</span></div><div className="board-card-meta"><span>Minimum trust {item.minimumTrustScore}</span><span>{item.payIdType} PayID</span></div><p>{item.notes || "No additional notes."}</p></article>) : <div className="empty-board">No lender availability yet. Start with what you can cover.</div>}</div></div></section>
      <section className="panel matches-panel"><div className="panel-heading"><div><p className="eyebrow"><span className="signal green" /> Confirmations</p><h2>Your matches</h2></div><Check size={21} /></div>{dashboard.data?.matches.length ? dashboard.data.matches.map((match) => <div className="match-row" key={match.id}><div><strong>{money(match.amountCents)}</strong><span>due {new Date(match.repaymentAt).toLocaleDateString("en-AU")}</span></div><span className={`status-pill status-${match.status}`}>{match.status}</span>{match.status !== "repaid" && <button className="button button-soft" onClick={() => confirmRepayment.mutate({ matchId: match.id })}>Confirm repayment</button>}</div>) : <p className="profile-copy">Matches appear here once both sides agree. Keep every repayment confirmation in the record.</p>}</section>
      <div className="boundary-note"><CircleAlert size={18} /><p><strong>Boundary first.</strong> This hub records posts, agreements, and confirmations. It never holds, sends, or guarantees money. Use PayID only after you have confirmed the member and agreed privately.</p></div>
    </main>
    {profileOpen && <div className="modal-backdrop" role="presentation"><div className="modal-card"><div className="panel-heading"><h2>Member profile</h2><button className="icon-button" onClick={() => setProfileOpen(false)}>×</button></div><div className="form-grid"><label>Display name<input value={profile.displayName} onChange={(e) => setProfile({ ...profile, displayName: e.target.value })} /></label><label>State<input value={profile.state} onChange={(e) => setProfile({ ...profile, state: e.target.value })} placeholder="e.g. NSW" /></label><label>Payday cycle<select value={profile.paydayCycle} onChange={(e) => setProfile({ ...profile, paydayCycle: e.target.value as typeof profile.paydayCycle })}><option value="weekly">Weekly</option><option value="fortnightly">Fortnightly</option><option value="monthly">Monthly</option></select></label><label>Here to<select value={profile.intent} onChange={(e) => setProfile({ ...profile, intent: e.target.value as typeof profile.intent })}><option value="borrow">Borrow</option><option value="lend">Lend</option><option value="both">Both</option></select></label><label>PayID type<select value={profile.payIdType} onChange={(e) => setProfile({ ...profile, payIdType: e.target.value as typeof profile.payIdType })}><option value="phone">Phone</option><option value="email">Email</option><option value="abn">ABN</option></select></label><label className="full-field">One thing about me<textarea value={profile.bio} onChange={(e) => setProfile({ ...profile, bio: e.target.value })} maxLength={500} /></label></div><button className="button button-primary" onClick={() => { submitProfile(); setProfileOpen(false); }}>Save profile</button></div></div>}
    {formOpen && <div className="modal-backdrop"><div className="modal-card"><div className="panel-heading"><h2>{formOpen === "request" ? "Post a loan request" : "Offer lender availability"}</h2><button className="icon-button" onClick={() => setFormOpen(null)}>×</button></div>{formOpen === "request" ? <div className="form-grid"><label>Amount in AUD<input type="number" min="1" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>Repayment date<input type="date" value={form.repaymentAt} onChange={(e) => setForm({ ...form, repaymentAt: e.target.value })} /></label><label>PayID type<select value={form.payIdType} onChange={(e) => setForm({ ...form, payIdType: e.target.value as typeof form.payIdType })}><option value="phone">Phone</option><option value="email">Email</option><option value="abn">ABN</option></select></label><label className="full-field">Notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} maxLength={500} /></label><button className="button button-primary" onClick={() => { submitRequest(); setFormOpen(null); }}>Post request <ArrowRight size={15} /></button></div> : <div className="form-grid"><label>Amount available in AUD<input type="number" min="1" value={offer.amount} onChange={(e) => setOffer({ ...offer, amount: e.target.value })} /></label><label>Available until<input type="date" value={offer.availableUntil} onChange={(e) => setOffer({ ...offer, availableUntil: e.target.value })} /></label><label>Minimum trust score<input type="number" min="0" max="100" value={offer.minimumTrustScore} onChange={(e) => setOffer({ ...offer, minimumTrustScore: e.target.value })} /></label><label>PayID type<select value={offer.payIdType} onChange={(e) => setOffer({ ...offer, payIdType: e.target.value as typeof offer.payIdType })}><option value="phone">Phone</option><option value="email">Email</option><option value="abn">ABN</option></select></label><label className="full-field">Notes<textarea value={offer.notes} onChange={(e) => setOffer({ ...offer, notes: e.target.value })} maxLength={500} /></label><button className="button button-primary" onClick={() => { submitOffer(); setFormOpen(null); }}>Post availability <ArrowRight size={15} /></button></div>}</div></div>}
  </div>;
}
